# Step 0: Benchmark Configuration

# How to sort distractors:
# simplification for draft: use random distractors, do not employ RUListening methodology (to be applied after Mar 30)
sorting_method: "dummy_shuffle"
sorting_methods_path: "src/distractor_sorting.py" # Add this to specify the python file with sorting methods

# simplification, use 5 always (including NOTA)
num_options: 5
nota_text: "none of the other options is correct"
add_nota: true

questions_per_subcategory_count: 20 # number of questions to generate per subcategory (for the draft, we can keep it small, e.g. 10, and then scale up after analyzing the results and iterating on the question templates)

ontology_path: "ontology.yaml" # Add this to specify the path to the ontology file

# If you specify a number here, the total number of 
# max_benchmark_items: 

# simplification for draft: only use final mix recordings, high-quality rendered PDF, and musicxml
submodalities:
  - "audio.mastermix.wav"
  - "visual.pdf"
  # - "visual.png"
  - "symbolic.musicxml"

# simplification: for the draft, pre-decided percentage of such questions (those that do not contain ground truth among the options), e.g. 20% if we use 5 options (then NOTA is correct as frequently as any other option), only focus on it on evaluation (discussion of results)
nota_correct_percentage: 0.20 # e.g., 20%
labels: ["A", "B", "C", "D", "E"]
seed: 42
min_num_distractors: 4
distractor_pool_size: 20 # number of distractors to sample from the ontology for each question (before sorting and selecting the final options)
random_distractors: true # whether to sample distractors randomly from the ontology (instead of using piece specific distractors)
cmdline_args:
  meta: "meta-questions-K.tsv"
  pieces: "pieces.tsv"
  methods_path: "src/ground_truth_and_distractor_pool_extractions.py"
  output: "benchmark_v1.tsv"

allowed_metaq_ids:
  - 4
  - 5
  - 6
  - 3
  - 2
  - 1
  - 0
  - 7
verbose: true
#use_all_inds: true # whether to use all indices for target_index (instead of just 1, 2, 3, end)
music_ontology_settings:
  ontology_path: "ontology.yaml"
  harmonic_system: "tonal"

balance_meta_questions_perfectly: false # whether the per-meta-question counts should be perfectly balanced in the per-subcategory count in the final subsampled benchmark

